- clean: [
    '~',
    '~/.mutt'
]

- link:
    ~/.dircolors: dircolors
    ~/.gitconfig: gitconfig
    ~/.jshintrc: jshintrc
    ~/.tmux: tmux
    ~/.tmux.conf: tmux.conf
    ~/.config/kitty: kitty
    ~/.config/nvim: nvim
    ~/.zshrc: zshrc

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1, Installing tmux plugins]
    - ["vim +PlugUpdate +PlugClean! +qa", Installing and updating plugins]
